import enum

class Token(enum.Enum):
    NEWLINE    = "\\n"
    COMMENT    = 'REM'
    LET        = 'LET'
    IF         = 'IF'
    THEN       = 'THEN'
    ELSEIF     = 'ELSEIF'
    ELSE       = 'ELSE'
    END        = 'END'
    FOR        = 'FOR'
    TO         = 'TO'
    STEP       = 'STEP'
    NEXT       = 'NEXT'
    PRINT      = 'PRINT'
    INPUT      = 'INPUT'
    EQUALS     = '='
    ADD        = '[+]'
    DIV        = '/'
    MUL        = '[*]'
    SUB        = '-'
    LPAR       = '[(]'
    RPAR       = '[)]'
    ID         = '[a-z_][a-z0-9_]*[$]?'
    NUM        = '[0-9]+'
    STR        = '"(([^"]|\\\\")*[^\\\\])?"'
